"""Builds src/token_data.lua: every token and emblem Scryfall has, so the table
never has to ask the relay for one (like planechase_data.lua for planes).
Run once (needs internet):   python tools/make_token_data.py
Run again whenever new sets come out. Writes src/token_data.lua.
Every token: name, type line, power, toughness, colors, rules text and the
Scryfall picture id. The picture itself still comes through your relay."""
import json
import os
import sys
import time
import urllib.parse
import urllib.request

UA = {"User-Agent": "mtg-tts-table/1.0 (token data builder)", "Accept": "application/json"}

QUERIES = [
    "layout:token",
    "layout:double_faced_token",
    "layout:emblem",
    "t:token",
    '!"The Monarch"',
    '!"The Initiative"',
    '!"The Ring"',
    '!"Day // Night"',
]


def get(url):
    for attempt in range(5):
        try:
            req = urllib.request.Request(url, headers=UA)
            with urllib.request.urlopen(req, timeout=60) as r:
                return json.load(r)
        except urllib.error.HTTPError as e:
            if e.code == 404:
                return {"data": [], "has_more": False}
            time.sleep(1.0 * (attempt + 1))
        except Exception:
            time.sleep(1.0 * (attempt + 1))
    raise SystemExit("Scryfall isn't answering: " + url)


def search(q):
    url = ("https://api.scryfall.com/cards/search?include_extras=true&unique=cards&order=released&dir=desc&q="
           + urllib.parse.quote(q))
    out = []
    while url:
        page = get(url)
        out.extend(page.get("data", []))
        url = page.get("next_page") if page.get("has_more") else None
        time.sleep(0.12)   # Scryfall asks for ~10 requests a second at most
    return out


def face0(card):
    faces = card.get("card_faces") or []
    if card.get("image_uris"):
        return card, card
    if faces and faces[0].get("image_uris"):
        return card, faces[0]
    return None, None


def lua(s):
    s = str(s)
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\r", "").replace("\n", "\\n") + '"'


seen, rows = set(), []
for q in QUERIES:
    cards = search(q)
    print("%-32s %d" % (q, len(cards)))
    for card in cards:
        top, f = face0(card)
        if f is None:
            continue
        uris = f.get("image_uris") or {}
        url = uris.get("large") or uris.get("normal") or uris.get("png")
        if not url:
            continue
        # .../front/a/b/<uuid>.jpg
        part = url.split("?")[0].rsplit("/", 1)[-1]
        sid = part.rsplit(".", 1)[0]
        name = f.get("name") or card.get("name")
        tl = f.get("type_line") or card.get("type_line") or ""
        p, t = f.get("power"), f.get("toughness")
        colors = "".join(f.get("colors") or card.get("colors") or [])
        oracle = f.get("oracle_text") or card.get("oracle_text") or ""
        key = (name, tl, p, t, colors, oracle)
        if key in seen:
            continue
        seen.add(key)
        rows.append((name, tl, p, t, colors, oracle, sid))

rows.sort(key=lambda r: (r[0].lower(), r[1], str(r[2]), str(r[3]), r[4]))
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "token_data.lua")
with open(path, "w", encoding="utf-8") as fh:
    fh.write("-- Generated by tools/make_token_data.py: every token and emblem, for tokens.lua.\n")
    fh.write("-- n name, t type line, p power, u toughness, c colors, o rules text, i Scryfall picture id.\n")
    fh.write("TOKEN_DATA = {\n")
    for name, tl, p, t, colors, oracle, sid in rows:
        fh.write("  { n = %s, t = %s%s%s, c = %s, o = %s, i = %s },\n" % (
            lua(name), lua(tl),
            (", p = " + lua(p)) if p is not None else "",
            (", u = " + lua(t)) if t is not None else "",
            lua(colors), lua(oracle), lua(sid)))
    fh.write("}\n")
print("%d tokens written to src/token_data.lua" % len(rows))
