"""Builds src/planechase_data.lua (the planes and phenomena for planechase.lua)
from a TTS table or saved object that has the planar decks.
Run: python tools/make_planechase_data.py path/to/table.json
Every card: name, image, type (Plane / Phenomenon), rules text, source group."""
import json
import sys

src = sys.argv[1]
d = json.load(open(src, encoding="utf-8"))


def find_bag(states):
    for o in states:
        if o.get("Nickname") == "Planechase" and o.get("ContainedObjects"):
            return o
        sub = o.get("ContainedObjects")
        if sub:
            r = find_bag(sub)
            if r:
                return r
    return None


bag = find_bag(d["ObjectStates"])
GROUPS = [  # deck nickname, group (first one listed wins for duplicate names)
    ("Planechase Anthology Planes", "classic"),
    ("Planechase MOC Planes", "classic"),
    ("Planechase Anthology/MOC Phenomena", "classic"),
    ("Planechase WHO Planes", "who"),
    ("Planechase WHO Phenomena", "who"),
]
cards, seen, back = [], set(), None
decks = {c["Nickname"]: c for c in bag["ContainedObjects"] if c.get("Name") == "Deck"}
for nick, group in GROUPS:
    deck = decks[nick]
    for c in deck["ContainedObjects"]:
        lines = c["Nickname"].split("\n")
        name = lines[0]
        kind = "Phenomenon" if "Phenomenon" in c["Nickname"] else "Plane"
        if name in seen:
            continue
        seen.add(name)
        cid = str(c["CardID"] // 100)
        cdk = c["CustomDeck"][cid] if cid in c["CustomDeck"] else list(c["CustomDeck"].values())[0]
        back = back or cdk["BackURL"]
        cards.append({"n": name, "u": cdk["FaceURL"], "t": kind, "g": group, "o": c.get("Description", "")})


def lua(s):
    return json.dumps(s, ensure_ascii=False)


out = ["-- Generated by tools/make_planechase_data.py: the planes and phenomena for planechase.lua.\n",
       "PLANECHASE_BACK = %s\n" % lua(back), "PLANECHASE_CARDS = {\n"]
for c in cards:
    out.append("  { n = %s, t = %s, g = %s,\n    u = %s,\n    o = %s },\n" % (lua(c["n"]), lua(c["t"]), lua(c["g"]), lua(c["u"]), lua(c["o"])))
out.append("}\n")
open("src/planechase_data.lua", "w", encoding="utf-8").write("".join(out))
print(len(cards), "cards;", sum(1 for c in cards if c["t"] == "Phenomenon"), "phenomena;", sum(1 for c in cards if c["g"] == "who"), "Doctor Who")
