-- Generated list of the table's music. Tell Claude to regenerate it when you add tracks.
MUSIC_TRACKS = {
  { title = "Zero Hour", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Act%201/01%20-%20Zero%20Hour.mp3" },
  { title = "Mobilize", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Act%201/02%20-%20Mobilize.mp3" },
  { title = "Sitrep", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Act%201/03%20-%20Sitrep.mp3" },
  { title = "Radio Silence", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Act%201/04%20-%20Radio%20Silence.mp3" },
  { title = "Contact Front", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Act%201/05%20-%20Contact%20Front.mp3" },
  { title = "Weapons Free", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Act%202/06%20-%20Weapons%20Free.mp3" },
  { title = "Danger Close", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Act%202/07%20-%20Danger%20Close.mp3" },
  { title = "Fire for Effect", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Act%202/08%20-%20Fire%20for%20Effect.mp3" },
  { title = "Hold the Line", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Act%202/09%20-%20Hold%20the%20Line.mp3" },
  { title = "No Man's Land", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Act%202/10%20-%20No%20Man%27s%20Land.mp3" },
  { title = "Kill Chain", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Act%203/11%20-%20Kill%20Chain.mp3" },
  { title = "Friendly Fire", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Act%203/12%20-%20Friendly%20Fire.mp3" },
  { title = "Scorched Earth", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Act%203/13%20-%20Scorched%20Earth.mp3" },
  { title = "Bonus 01: Alpha - R", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Bonus%20-%2001%20-%20Alpha%20-%20R.mp3" },
  { title = "Bonus 02: Beta - R", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Bonus%20-%2002%20-%20Beta%20-%20R.mp3" },
  { title = "Bonus 03: Gamma - R", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Bonus%20-%2003%20-%20Gamma%20-%20R.mp3" },
  { title = "Bonus 04: Delta - R", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Bonus%20-%2004%20-%20Delta%20-%20R.mp3" },
  { title = "Bonus 05: Epsilon - R", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Bonus%20-%2005%20-%20Epsilon%20-%20R.mp3" },
  { title = "Bonus 06: Zeta - R", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Bonus%20-%2006%20-%20Zeta%20-%20R.mp3" },
  { title = "Bonus 07: Eta - R", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Bonus%20-%2007%20-%20Eta%20-%20R.mp3" },
  { title = "Bonus 08: Omicron - R", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Bonus%20-%2008%20-%20Omicron%20-%20R.mp3" },
  { title = "Bonus 09: Rho - R", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Bonus%20-%2009%20-%20Rho%20-%20R.mp3" },
  { title = "Bonus 10: Sigma - R", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Bonus%20-%2010%20-%20Sigma%20-%20R.mp3" },
  { title = "Bonus 11: Phi - R", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Bonus%20-%2011%20-%20Phi%20-%20R.mp3" },
  { title = "Bonus 12: Sigma", url = "https://raw.githubusercontent.com/NutritiousDeath/mtg-tts-table/main/assets/music/MP3_for_TTS/Remixed/Bonus%20-%2012%20-%20Sigma.mp3" },
}
